apiVersion: v1
kind: Service
metadata:
 name: flask-service-nodeport
 
spec:
 type: NodePort
 ports:
   - port: 5000
     targetPort: 5000
     nodePort: 30010
 selector:
   app: flask
   tier: frontend